sudo: required
services:
  - docker

before_install:
  - docker build -t fintanmcevoy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fintanmcevoy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-272948695360"
  bucket_path: "docket-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY